### ISSUE TITLE
'Meet the Team' Series - Pat Heard

### ISSUE THREAD

**Issue by britthurley** [SSC-CIO-DigitalTaskForce/reading-material#2]
In order to introduce people to the team, we will host a series of 'Meet the DTF' sessions.

The purpose will be to inform others of the Experience, Skillset, and motivations of the DTF team members in order to more effectively market our services.

The format, and style of these presentations are completely up to the team member to design as they see fit - no expectations or limitations.

As the Technical Lead, Pat will be first up to the plate.

**Comment by patheard** [comment]
@britthurley I put my presentation together using [reveal.js](https://github.com/hakimel/reveal.js) and markdown to play around with the idea of a presentation that could have its text changes tracked by git.

Open up [the-team/pat-heard/index.html](https://github.com/SSC-CIO-DigitalTaskForce/reading-material/blob/master/the-team/pat-heard/index.html) in Chrome and let me know if this is what you were thinking for the series.  Totally open to tweaks and changes.

There are a few more small style things I want to change, but the content is mostly done.

**Comment by britthurley** [comment]
Looks good, and love that you did it as code!

One thing i'd like you to add is some projects you've worked on that reflect your skills - also wouldn't mind you highlighting your previous with with the WET project, as a bit of a nudge to open source and collaboration.

**Comment by patheard** [comment]
I've finished the content @britthurley.  Let me know what you think!

The last thing I want to do is add a built process to fix the last of the Chrome performance audit issues, but this is def a low priority, so I'm going to but it on the back burner and track with a new issue.

**Comment by patheard** [comment]
I published a `gh-pages` branch for the `reading-material` repo, so you can now see my deck here:

https://ssc-cio-digitaltaskforce.github.io/reading-material/the-team/pat-heard/
