### ISSUE TITLE
DTF Branding

### ISSUE THREAD

**Issue by britthurley** [SSC-CIO-DigitalTaskForce/reading-material#4]
We should brand our material. Things we'd need:

- Logo
- Powerpoint Template

Our branding should try to connect with CIO/SSC branding.

**Comment by patheard** [comment]
Here's a logo idea I put together this morning.  I've got a few more concepts I'm going to work on this afternoon and tomorrow morning.

Totally open to feedback on this!  Consider it a rough draft.

My thinking behind it was:

* Century Gothic font, circles and simple shapes to match SSC 3.0 branding.
* Pull the blue/purple gradient into a footer banner for our templates.  Could also use different gradients to delineate sections of a presentation (e.g. all slides in a given section would use same gradient).
* Play with more, simple, overlapping shapes as a subtle pattern in the footer banner.

---

![dtf-logo_v1a](https://user-images.githubusercontent.com/2110107/64364521-04679800-cfe1-11e9-8c7b-d037d73bef6e.png)

**Comment by patheard** [comment]
If you're curious, these are sketches of the other ideas I'll be working on:

![ideas](https://user-images.githubusercontent.com/2110107/64365545-5e1c9200-cfe2-11e9-835b-dfcdfa8aa751.jpg)

**Comment by patheard** [comment]
More concepts:

---

![dtf-logo_v1b](https://user-images.githubusercontent.com/2110107/64374493-fbcb8d80-cff1-11e9-9e9f-b0480f61ddc3.png)

**Comment by patheard** [comment]
Last option we can show Shannon today.  My favorites are the chevrons and these checkmarks.  I think the first checkmark I did is a bit aggro with all the sharp edges:

---

![dtf-logo_v1c](https://user-images.githubusercontent.com/2110107/64434552-c923a280-d08e-11e9-8f56-b99e49316f0e.png)

---

Totally open to colours/text as well.  We could make any of these work with different colours and wording/layout.

**Comment by patheard** [comment]
Based on the meeting, I'm going to:

* Put together some text layout variants for v1c; and
* Start working on presentation and doc templates.

**Comment by patheard** [comment]
v2 of the logo finished.  It's just:

* Minor tweaks to colour; 
* Horizontal text layout; and
* Isolated checkmark.

I'll start working this into presentation/doc templates on Monday.

---

![dtf-logo_v2](https://user-images.githubusercontent.com/2110107/64458996-d196d000-d0c4-11e9-98f8-2b3a81e3af0f.png)

**Comment by britthurley** [comment]
ll of v2 looks amazing! Can't wait to use these!! STICKERS!

**Comment by patheard** [comment]
Here's a first version of our Powerpoint template.   It's based heavily on the standard SSC 3.0 Powerpoint template:

https://github.com/SSC-CIO-DigitalTaskForce/reading-material/blob/master/branding/templates/widescreen-template.pptx?raw=true

**Comment by britthurley** [comment]
I love this so much! Great job :)

**Comment by patheard** [comment]
Thanks :)

Do you want a standard width template too?  Wouldn't take long to make, but I'm not sure when we'd use it.

**Comment by britthurley** [comment]
No, I wouldn't worry about it. I don't think we will use it, and if we need
it you can put it together at that time.
